spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/cartdb
    username: root
    password: Ramcharan8@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
